Resources:    
  MyUser:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/job-function/ViewOnlyAccess"
      Policies:
        - PolicyName: MyExamplePolicy
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
                - Sid: IamListAccess
                  Effect: Allow
                  Action:
                  - 'iam:ListRoles'
                  - 'iam:ListUsers'
                  Resource: '*'
  MyInlinePolicy:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-policies
    Type: 'AWS::IAM::UserPolicy'
    Properties:
      PolicyName: MyInlinePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'ec2:*'
            Resource: '*'
      UserName: !Ref MyUser
  MySecondInlinePolicy:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-userpolicy.html
    Type: 'AWS::IAM::UserPolicy'
    Properties:
      PolicyName: MySecondInlinePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
      UserName: !Ref MyUser