#!/usr/bin/env bash

echo "== deploy rds"

STACK_NAME="rds-basic"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--parameter-overrides \
    VpcId="<vpc-id>" \
    WebServerSGGroupId="<sg-id>" \
    RdsSecretArn="<secret-arn>" \
    Username="boscoting" \
    Subnets="<subnet-id-1>,<subnet-id-2>,<subnet-id-3>" \
--region ap-northeast-1 \
--stack-name $STACK_NAME

