#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name file-prefix"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix eg. ./bucket my-bucket-name file-prefix"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$(basename $2)  # Extract the base name to avoid directory components

OUTPUT_DIR="/tmp/s3_bash_scripts"

if [ -d "$OUTPUT_DIR" ]; then
  rm -rf "$OUTPUT_DIR"
  echo "Removed existing directory: $OUTPUT_DIR"
fi

mkdir -p $OUTPUT_DIR

# Function to print usage
usage() {
  echo "Usage: $0 <bucket_name> <filename_prefix> <number_of_files>"
  echo "number_of_files should be between 1 and 5."
  exit 1
}

# Check if an argument is provided for the number of files
if [ -z "$3" ]; then
  usage
fi

# Check if the argument is a number between 1 and 5
if ! [[ "$3" =~ ^[1-5]$ ]]; then
  usage
fi

# Create the specified number of files
number_of_files=$3
for i in $(seq 1 $number_of_files); do
  file_name="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"
  touch "${file_name}"
  echo "Created ${file_name}"
done

echo "Successfully created $number_of_files files."
tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files
