#! /usr/bin/env bash

echo "==deploy ec2"
 
STACK_NAME="aws-asg-ec2-basic"

# Since Osaka doesn't provide auto-scaling service, use ap-northeast-1 here instead
aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region ap-northeast-1 \
--stack-name $STACK_NAME